package thunder.hack.utility.render;

import net.minecraft.resources.ResourceLocation;

public final class TextureStorage {
    public static final ResourceLocation crystalTexture2 = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/misc/end_crystal2.png");
    public static final ResourceLocation skull = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/skull.png");
    public static final ResourceLocation star = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/star.png");
    public static final ResourceLocation heart = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/heart.png");
    public static final ResourceLocation dollar = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/dollar.png");
    public static final ResourceLocation snowflake = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/snowflake.png");
    public static final ResourceLocation firefly = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/firefly.png");
    public static final ResourceLocation arrow = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/triangle.png");
    public static final ResourceLocation capture = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/capture.png");
    public static final ResourceLocation bubble = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/hitbubble.png");
    public static final ResourceLocation default_circle = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/particles/circle.png");
    public static final ResourceLocation container = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/container.png");
    public static final ResourceLocation guiArrow = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/arrow.png");
    public static final ResourceLocation Gear = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/headers/client.png");
    public static final ResourceLocation candle = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/candle.png");
    public static final ResourceLocation thTeam = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/thteam.png");
    public static final ResourceLocation donation = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/donationalerts.png");
    public static final ResourceLocation chestIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/chest.png");
    public static final ResourceLocation brokenShield = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/broken_shield.png");
    public static final ResourceLocation miniLogo = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/mini_logo.png");
    public static final ResourceLocation playerIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/headers/player.png");
    public static final ResourceLocation serverIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/server.png");
    public static final ResourceLocation proxyIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/proxy.png");
    public static final ResourceLocation waypoint = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/waypoint.png");
    public static final ResourceLocation configIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/configpng.png");
    public static final ResourceLocation waypointIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/waypointicon.png");
    public static final ResourceLocation macrosIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/macrosicon.png");
    public static final ResourceLocation speedometerIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/speedometer.png");
    public static final ResourceLocation lagIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/lag.png");
    public static final ResourceLocation fpsIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/fps.png");
    public static final ResourceLocation pingIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/ping.png");
    public static final ResourceLocation swordIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/sword.png");
    public static final ResourceLocation memoryIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/memory.png");
    public static final ResourceLocation tpsIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/tps.png");
    public static final ResourceLocation boykisser = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/boykisser.png");
    public static final ResourceLocation paimon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/paimon.png");
    public static final ResourceLocation baltika = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/baltika.png");
    public static final ResourceLocation kowk = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/kowk.png");
    public static final ResourceLocation thLogo = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/mh.png");
    public static final ResourceLocation thudPic = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/elements/thud.png");
    public static final ResourceLocation coordsIcon = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/hud/icons/coords.png");
    public static final ResourceLocation sunRiseSkin = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/misc/sunskin.png");
    public static final ResourceLocation crackedSkin = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/elements/cracked.png");
    public static final ResourceLocation questionPic = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/helper/pic1.png");
    public static final ResourceLocation cutie = ResourceLocation.fromNamespaceAndPath("thunderhack", "textures/gui/images/cutie.png");
}
